name: Windows Ready for Manual Download

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Tailscale & VirtualBox
        shell: powershell
        run: |
          choco install tailscale virtualbox -y
          Start-Sleep -Seconds 5
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-vbox

      - name: Setup RDP Access
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          $Password = ConvertTo-SecureString "Password123!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $Password

      - name: Keep Alive
        shell: powershell
        run: |
          Write-Host "Connect now and download the ISO inside the machine!"
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4
          Start-Sleep -Seconds 21600
